### ISSUE TITLE
Szlovénia felvétele az országlistába

### ISSUE THREAD

**Issue by LetsCloud** [LetsCloud/com.letscloud.expresscheckin#2]
Szlovénia az EU tagja, ezért feltétlenül szerepelnie kell az országlistábban.

**Comment by LetsCloud** [comment]
Egyeztetni kell a lsitában elfoglalandó sorrendről

**Comment by LetsCloud** [comment]
Hello CloudRobi!
El tudsz készülni a jövő héten?
Üdv:
LC

**Comment by CloudRobi** [comment]
Szerintem igen.
Üdv,
CR

**Comment by LetsCloud** [comment]
Átveszem

**Comment by LetsCloud** [comment]
Change-Id: Id588c66ae4bcd9354b4f394aa9a43c479f047e87
